### ISSUE TITLE
SteamSettings connection lost on multi target games

### ISSUE THREAD

**Issue by mike-petersen** [heathen-engineering/SteamworksFoundation#2]
Hi,
i have a vr game that is currently released on steam. I also want to release it for the Quest 2 (Android). Cause Steamworks is not supported there the classes do not exist (condition in source !DISABLESTEAMWORKS && HE_SYSCORE && (STEAMWORKSNET || FACEPUNCH)).

Due too that there are broken scripts in the scene. If i am now on the android platform and make changes to the scene, Unity removes the reference to the StatObjects. Due too that, the next build on windows for steam will break the steam stat object handling.

Is there a way to work around this?

**Comment by JamesMcGhee** [comment]
Yes this is expected behaviour and a challenge of multi-platform development

We have [articles](https://kb.heathen.group/company/development/multi-platform-projects) on the options available to you.
You can also join our [Discord](https://discord.gg/6X3xrRc) and chat with others that have worked on similar.

In short if your going to build a multi-platform project ... that also integrates with platform specific features you have to define a means to differentiate your code. Rather you use parallel development and branches, or use build processes and conditional compilation or whatever else it is up to you to handle that. Our [guides](https://kb.heathen.group/company/development/multi-platform-projects), and [community](https://discord.gg/6X3xrRc) might be of some help getting started with that.

As this isn't a bug or issue with the tool I will close this thread but do encourage you to read over our [articles](https://kb.heathen.group/company/development/multi-platform-projects) and join our [community](https://discord.gg/6X3xrRc) and chat there.
